"""initial schema

Revision ID: fe7fce7ba8ae
Revises: 
Create Date: 2026-03-30 16:01:03.991867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe7fce7ba8ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boss_raids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('boss_name', sa.String(length=100), nullable=True),
    sa.Column('boss_hp', sa.Integer(), nullable=True),
    sa.Column('boss_max_hp', sa.Integer(), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('time_limit_days', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('cleared_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boss_raids_id'), 'boss_raids', ['id'], unique=False)
    op.create_table('gates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('gate_rank', sa.Enum('e_rank', 'd_rank', 'c_rank', 'b_rank', 'a_rank', 's_rank', 'ss_rank', 'monarch', name='hunterrank'), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=True),
    sa.Column('time_limit_hours', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('objective_type', sa.String(length=50), nullable=True),
    sa.Column('objective_target', sa.Integer(), nullable=True),
    sa.Column('objective_current', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('cleared_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gates_creator_id'), 'gates', ['creator_id'], unique=False)
    op.create_index(op.f('ix_gates_id'), 'gates', ['id'], unique=False)
    op.add_column('contacts', sa.Column('shadow_grade', sa.String(length=20), nullable=True))
    op.add_column('contacts', sa.Column('shadow_extracted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('hunter_rank', sa.Enum('e_rank', 'd_rank', 'c_rank', 'b_rank', 'a_rank', 's_rank', 'ss_rank', 'monarch', name='hunterrank'), nullable=True))
    op.add_column('users', sa.Column('stat_points', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('stat_charisma', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('stat_empathy', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('stat_consistency', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('stat_initiative', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('stat_wisdom', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('shadow_army_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('daily_quest_streak', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('hp', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('title', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('streak_freezes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'streak_freezes')
    op.drop_column('users', 'title')
    op.drop_column('users', 'hp')
    op.drop_column('users', 'daily_quest_streak')
    op.drop_column('users', 'shadow_army_count')
    op.drop_column('users', 'stat_wisdom')
    op.drop_column('users', 'stat_initiative')
    op.drop_column('users', 'stat_consistency')
    op.drop_column('users', 'stat_empathy')
    op.drop_column('users', 'stat_charisma')
    op.drop_column('users', 'stat_points')
    op.drop_column('users', 'hunter_rank')
    op.drop_column('contacts', 'shadow_extracted_at')
    op.drop_column('contacts', 'shadow_grade')
    op.drop_index(op.f('ix_gates_id'), table_name='gates')
    op.drop_index(op.f('ix_gates_creator_id'), table_name='gates')
    op.drop_table('gates')
    op.drop_index(op.f('ix_boss_raids_id'), table_name='boss_raids')
    op.drop_table('boss_raids')
    # ### end Alembic commands ###
